- name: install JDK
  yum: name="java-{{JDK_VERSION}}-openjdk-devel" state=latest

- name: off swap
  command: swapoff -a 

- name: off swap1
  lineinfile: path=/etc/fstab regexp="swap" line="^#.*swap.*"  backup=yes

- name: create package Directory
  file: path=/data/soft state=directory

- name: download zookeeper
  get_url: url="http://yum.itestcn.com/github/zookeeper/release/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz" dest="/data/soft/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz"

- name: unarchive zookpeeper
  unarchive: src="/data/soft/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz" dest=/data/ copy=no

- name: rename zookeeper directory
  command: mv "/data/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin" /data/zookeeper

- name: create zookeeper db directory
  file: path=/data/zookeeper/db state=directory

- name: create zookeeper logs directory
  file: path=/data/zookeeper/logs state=directory

- name: zookpeeper config
  template: src=zoo.cfg.j2 dest=/data/zookeeper/conf/zoo.cfg
 
  notify: restart zookeeper

- name: zookeeper serviceconfig
  template: src=zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service

- name: just force systemd to reread
  systemd: daemon_reload=yes


- name: start zookeeper service 
  service: name=zookeeper enabled=true state=started


- name: download kafka
  get_url: url="http://yum.itestcn.com/github/kafka/release/kafka_{{KAFKA_VERSION}}.tgz" dest="/data/soft/kafka_{{KAFKA_VERSION}}.tgz"

- name: unarchive kafka
  unarchive: src="/data/soft/kafka_{{KAFKA_VERSION}}.tgz" dest=/data/ copy=no

- name: rename fafka
  command: mv /data/kafka_{{KAFKA_VERSION}} /data/kafka

- name: create kafka logs directory
  file: path=/data/kafka/logs state=directory

- name: kafka config 
  template: src=kafka.config.j2 dest=/data/kafka/config/server.properties 

- name: kafka service 
  template: src=kafka.service.j2 dest=/usr/lib/systemd/system/kafka.service

- name: just force systemd to reread
  systemd: daemon_reload=yes


- name: start zookeeper service 
  service: name=kafka enabled=true state=started

