---
# tasks file for Active-Standby-es

- name: create package Directory
  file: path=/data/soft state=directory

- name: off swap
  command: swapoff -a

- name: off swap1
  lineinfile: path=/etc/fstab regexp="swap" line="^#.*swap.*"  backup=yes

- name: 降低交换
  sysctl:
   name: vm.swappiness
   value: 1
   sysctl_set: yes

- name: 设置虚拟内存
  sysctl:
   name: vm.max_map_count
   value: 262144
   sysctl_set: yes
   reload: yes

- name: add user elasticsearch
  user: name=elasticsearch state=present

- name: add limits 设置打开文件数量限制 root用户级别
  lineinfile:
   dest: /etc/security/limits.conf
   line: 'elasticsearch - nofile 65535'

- name: add limits 设置线程限制 root用户级别
  lineinfile:
   dest: /etc/security/limits.conf
   line: 'elasticsearch - nproc 4096'

- name: add limits1 设置锁定内存权限 root用户级别
  lineinfile:
   dest: /etc/security/limits.conf
   line: elasticsearch soft memlock unlimited

- name: add limits2 设置锁定内存权限 root用户级别
  lineinfile:
   dest: /etc/security/limits.conf
   line: elasticsearch hard memlock unlimited

- name: download es
#  get_url: url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ES_VERSION}}-linux-x86_64.tar.gz" dest="/data/soft/elasticsearch-{{ES_VERSION}}-linux-x86_64.tar.gz"
  get_url: url="http://yum.itestcn.com/github/elasticsearch/release/elasticsearch-{{ES_VERSION}}-linux-x86_64.tar.gz" dest="/data/soft/elasticsearch-{{ES_VERSION}}-linux-x86_64.tar.gz"
  tags:
  - download es

- name: unarchive es
  unarchive: src="/data/soft/elasticsearch-{{ES_VERSION}}-linux-x86_64.tar.gz" dest=/data/ copy=no


- name:  es_Xms
  lineinfile:
   dest: /data/elasticsearch-{{ES_VERSION}}/config/jvm.options
   regexp: "^-Xms"
   line: "-Xms{{ES_memory}}"

- name:  es_Xms
  lineinfile:
   dest: "/data/elasticsearch-{{ES_VERSION}}/config/jvm.options"
   regexp: "^-Xmx"
   line: "-Xmx{{ES_memory}}"

- name: config elasticsearch master
  template: 
   src: elasticsearch.yml.j2
   dest: /data/elasticsearch-{{ES_VERSION}}/config/elasticsearch.yml

- name: download ik 分词
  #get_url: url="https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v{{ES_VERSION}}/elasticsearch-analysis-ik-{{ES_VERSION}}.zip" dest=/data/soft/
  get_url: url="http://yum.itestcn.com/github/elasticsearch/release/elasticsearch-analysis-ik-{{ES_VERSION}}.zip" dest=/data/soft/

- name: create ik directory
  file: path="/data/elasticsearch-{{ES_VERSION}}/plugins/ik" state=directory

- name: unarchive ik 
  unarchive: src="/data/soft/elasticsearch-analysis-ik-{{ES_VERSION}}.zip" dest="/data/elasticsearch-{{ES_VERSION}}/plugins/ik" copy=no

- name: install jdk
  yum: name="java-{{JDK_version}}-openjdk-devel" state=latest

- name: 修改es 属主属组
  file: path="/data/elasticsearch-{{ES_VERSION}}" group=elasticsearch owner=elasticsearch recurse=yes

- name: 做成服务
  template: src=elasticsearch.service.j2 dest=/usr/lib/systemd/system/elasticsearch.service 

- name: just force systemd to reread
  systemd: daemon_reload=yes

- name: start elasticsearch
  systemd: name=elasticsearch enabled=true state=started

- name: download kibana
  get_url: url="http://yum.itestcn.com/github/elasticsearch/release/kibana-{{ES_VERSION}}-linux-x86_64.tar.gz" dest=/data/soft

- name: unarchive kibana
  unarchive: src=/data/soft/kibana-{{ES_VERSION}}-linux-x86_64.tar.gz dest=/data/ copy=no

- name: 修改 kibana 目录名
  command: mv /data/kibana-{{ES_VERSION}}-linux-x86_64 /data/kibana-{{ES_VERSION}}

- name: kibana config 
  template: 
   src: kibana.yml.j2 
   dest: /data/kibana-{{ES_VERSION}}/config/kibana.yml

- name: 修改es 属主属组
  file: path="/data/kibana-{{ES_VERSION}}" group=elasticsearch owner=elasticsearch recurse=yes

- name: kibana service
  template: src=kibana.service.j2 dest=/usr/lib/systemd/system/kibana.service 

- name: just force systemd to reread
  systemd: daemon_reload=yes
- name: start kibana
  systemd: name=kibana enabled=true  state=started
