---
- name: create package Directory
  file: path=/data/ state=directory

- name: add user elasticsearch
  user: name=elasticsearch state=present

- name: 推送kibana二进制文件
  unarchive: src="kibana-{{KIBANA_VERSION}}-linux-x86_64.tar.gz" dest=/data/

- name: 重命名kibana
  shell: |
    cd /data/
    if [ ! -d kibana-{{KIBANA_VERSION}} ];then
       mv kibana-{{KIBANA_VERSION}}-linux-x86_64 /data/kibana-{{KIBANA_VERSION}}
    fi

#- name: 修改 kibana 目录名
#  command: mv /data/kibana-{{ES_VERSION}}-linux-x86_64 /data/kibana-{{ES_VERSION}}

- name: kibana config 
  template: 
   src: kibana.yml.j2 
   dest: /data/kibana-{{KIBANA_VERSION}}/config/kibana.yml

- name: 修改es 属主属组
  file: path="/data/kibana-{{KIBANA_VERSION}}" group=elasticsearch owner=elasticsearch recurse=yes

- name: kibana service
  template: src=kibana.service.j2 dest=/usr/lib/systemd/system/kibana.service 

- name: just force systemd to reread
  systemd: daemon_reload=yes
- name: start kibana
  systemd: name=kibana enabled=true  state=started
