- hosts: 192.168.228.208
  remote_user: root
  
  tasks:
#   - name: test
#     shell: "ping -c 1 {{item}} | grep icmp_seq | gawk -F'[()]' '{print $2}'"
#     with_inventory_hostnames: test2
#     register: testip
#   
#   - name: test2
#     debug: "msg={{ item.stdout }}"
#     with_items: "{{ testip.results }}"
# tasks file for mysql
    - name: download mysql yum Repository
      get_url: url=http://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm dest=/opt/mysql57-community-release-el7-10.noarch.rpm
      tags:
       - donwload mysql yum Repository

    - name: install mysql yum Repository
      yum: name=/opt/mysql57-community-release-el7-10.noarch.rpm state=installed
      tags:
       - mysqlyumRepository

