- name: install JDK
  yum: name="java-{{JDK_VERSION}}-openjdk-devel" state=latest

- name: off swap
  command: swapoff -a 

- name: off swap1
 #replace:
 # path: /etc/fstab
 # regexp: ".*swap.*"
 # replace: "#.*swap.*"
  command: sed -i 's/.*swap.*/#&/' /etc/fstab

- name: create package Directory
  file: path=/data/soft state=directory

- name: download zookeeper
  get_url: url="http://yum.itestcn.com/github/zookeeper/release/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz" dest="/data/soft/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz"

 #https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz

- name: unarchive zookpeeper
  unarchive: src="/data/soft/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin.tar.gz" dest=/data/ copy=no

- name: rename zookeeper directory
  command: mv "/data/apache-zookeeper-{{ZOOKEEPER_VERSION}}-bin" /data/zookeeper

- name: create zookeeper db directory
  file: path=/data/zookeeper/db state=directory

- name: create zookeeper logs directory
  file: path=/data/zookeeper/logs state=directory

- name: zookpeeper config
  template: src=zoo.cfg.j2 dest=/data/zookeeper/conf/zoo.cfg
 
  notify: restart zookeeper

- name: zookeeper serviceconfig
  template: src=zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service

- name: just force systemd to reread
  systemd: daemon_reload=yes


- name: start zookeeper service 
  service: name=zookeeper enabled=true state=started


- name: download kafka
  get_url: url="http://yum.itestcn.com/github/kafka/release/kafka_{{KAFKA_VERSION}}.tgz" dest="/data/soft/kafka_{{KAFKA_VERSION}}.tgz"

- name: unarchive kafka
  unarchive: src="/data/soft/kafka_{{KAFKA_VERSION}}.tgz" dest=/data/ copy=no

- name: rename fafka
  command: mv /data/kafka_{{KAFKA_VERSION}} /data/kafka

- name: create kafka logs directory
  file: path=/data/kafka/logs state=directory

- name: kafka config1
  lineinfile: path=/data/kafka/config/server.properties  regexp="^broker.id" line="broker.id=0"

- name: kafka config2
  lineinfile: path=/data/kafka/config/server.properties  regexp="^#listeners" line="listeners=PLAINTEXT://{{ansible_all_ipv4_addresses[1]}}:9092"

- name: kafka config3
  lineinfile: path=/data/kafka/config/server.properties  regexp="^#advertised.listeners" line="advertised.listeners=PLAINTEXT://{{ansible_all_ipv4_addresses[1]}}:9092"
  
- name: kafka config4
  lineinfile: path=/data/kafka/config/server.properties  regexp="^log.dirs" line="log.dirs=/data/kafka/logs"

- name: kafka config5
  lineinfile: path=/data/kafka/config/server.properties  regexp="^zookeeper.connect=" line="zookeeper.connect={{ansible_all_ipv4_addresses[1]}}:2181"

- name: kafka service 
  template: src=kafka.service.j2 dest=/usr/lib/systemd/system/kafka.service

- name: just force systemd to reread
  systemd: daemon_reload=yes


- name: start zookeeper service 
  service: name=kafka enabled=true state=started

