#- name: install JDK
#  yum: name="java-{{JDK_VERSION}}-openjdk-devel" state=latest

- name: off swap
  command: swapoff -a 

- name: off swap1
  lineinfile: path=/etc/fstab regexp="swap" line="^#.*swap.*"  backup=yes

- name: create package Directory
  file: path=/data/ state=directory

- name: 推送 kafka 二进制文件
  unarchive: src="kafka_{{KAFKA_VERSION}}.tgz" dest=/data/

- name: 重命名  kafka
  shell: |
      cd /data/
      if [ ! -d kafka ];then
          mv kafka_{{KAFKA_VERSION}} kafka
      fi

- name: create kafka logs directory
  file: path="{{Kafka_dir}}/logs" state=directory

- name: kafka server.properties
  template: src=kafka.server.properties.j2 dest="{{Kafka_dir}}/config/server.properties"
 
  notify: restart kafka

- name: kafka producer.properties
  template: src=producer.properties.j2 dest="{{Kafka_dir}}/config/producer.properties"
  
  notify: restart kafka

- name: kafka consumer.properties
  template: src=consumer.properties.j2 dest="{{Kafka_dir}}/config/consumer.properties"
  
  notify: restart kafka 

- name: kafka service 
  template: src=kafka.service.j2 dest=/usr/lib/systemd/system/kafka.service

- name: just force systemd to reread
  systemd: daemon_reload=yes


- name: start zookeeper service 
  systemd: name=kafka enabled=true state=started

