---
# tasks file for k8s_etcd
- name: install ntp 
  yum: name=ntp state=latest update_cache=yes

- name: sync date
  shell: /usr/sbin/ntpdate  cn.pool.ntp.org

- name: download cfssl
  get_url: url=https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 dest=/usr/local/bin/cfssl mode=755

- name: download cfssljson
  get_url: url=https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64 dest=/usr/local/bin/cfssljson mode=755

- name: download cfssl-certinfo
  get_url: url=https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64 dest=/usr/bin/cfssl-certinfo mode=755

- name: create etcd 证书工作目录
  file: path=/root/TLS/etcd/ state=firectory

- name: create etcd 证书工作目录
  file: path=/root/TLS/etcd/ state=firectory

- name: ca-config
  template: src=ca-config.json.j2 dest=/root/TLS/etcd/ca-config.json

- name: ca-csr
  template: src=ca-csr.json.j2 dest=/root/TLS/etcd/ca-csr.json

- name: 生成证书
  shell: cd /root/TLS/etcd/ && /usr/local/bin/cfssl gencert -initca ca-csr.json | cfssljson -bare ca -

- name: server-csr
  template: src=server-csr.json.j2 dest=/root/TLS/etcd/server-csr.json

- name: 生成证书
  shell: cd /root/TLS/etcd/ && /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=www server-csr.json | cfssljson -bare server

- name: create package directory
  file: path=/data/soft state=directory

- name: download etcd
  get_url: url="https://github.com/etcd-io/etcd/releases/download/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz" dest=/data/soft

- name: create etcd bin
  file: path=/opt/etcd/bin state=directory

- name: create etcd cfg
  file: path=/opt/etcd/cfg state=directory

- name: create etcd ssl
  file: path=/opt/etcd/ssl state=directory

- name: unarchive etcd
  unarchive: src="/data/soft/etcd-{{etcd_version}}-linux-amd64.tar.gz" dest=/data/soft/

- name: copy etcd
  shell: scp "/data/soft/etcd-{{etcd_version}}-linux-amd64/etcd" /opt/etcd/bin

- name: copy etcd
  shell: scp "/data/soft/etcd-{{etcd_version}}-linux-amd64/etcdctl" /opt/etcd/bin

- name: etcd conf
  template: src=etcd.conf.j2 dest=/opt/etcd/cfg/etcd.conf 

- name: etcd service 
  template: src=etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service


