---
# tasks file for ha_keepalived
- name: 安装haproxy keepalived
  yum: 
   name: ['haproxy','keepalived','psmisc','mailx']
   state: latest
   update_cache: yes

- name: 推送master01 keepalived配置文件
  template: src=master01_keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: ansible_default_ipv4.address == (Master01)
  notify: restart keepalived

- name: 推送master02 keepalived配置文件
  template: src=master02_keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: ansible_default_ipv4.address == (Master02)
  notify: restart keepalived

- name: 推送master03 keepalived配置文件
  template: src=master03_keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: ansible_default_ipv4.address == (Master03)
  notify: restart keepalived

- name: 推送haproxy配置文件
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: 推送检测脚本
  copy: src=check_haproxy.sh dest=/etc/keepalived/check_haproxy.sh  mode=0755

- name: 推送ipvs模块
  copy: src=ipvs.modules dest=/etc/sysconfig/modules/ipvs.modules mode=0755

- name: 开启ipvs模块
  shell: bash /etc/sysconfig/modules/ipvs.modules

- name: 启动 keepalived
  systemd: name=keepalived enabled=yes state=started

- name: 启动haproxy
  systemd: name=haproxy enabled=yes state=started
