- name: chkfig off iptables
  shell: /sbin/chkconfig iptables off

- name: stop iptables
  service: name=iptables state=stopped

- name: chkfig off sendmail
  shell: /sbin/chkconfig sendmail off

- name: stop sendmail
  service: name=sendmail state=stopped

- name: sed selinux
  shell: /usr/bin/sed -i 's#SELINUX=enforcing#SELINUX=disabled#g' /etc/selinux/config

- name : stop selinux
  command: /sbin/setenforce 0
