#- name: chkfig off iptables
#  shell: /sbin/chkconfig iptables off

- name: stop iptables
  service: name=firewalld state=stopped enabled=no

#- name: chkfig off sendmail
#  shell: /sbin/chkconfig sendmail off

#- name: stop sendmail
#  service: name=sendmail state=stopped enabled=no

- name:  replace selinux
#  shell: /usr/bin/sed -i 's#SELINUX=enforcing#SELINUX=disabled#g' /etc/selinux/config
  replace: path=/etc/selinux/config regexp="SELINUX=enforcing" replace="SELINUX=disabled" 

- name : stop selinux
  command: /sbin/setenforce 0
