- name: install package
  yum: name={{item}} state=present
  with_items:
  - vim
  - man
  - gcc
  - gcc-c++
  - wget
- name: install package1
  yum: name={{item}}
  with_items:
  - tree
  - dos2unix
  - ipmitool
  - lrzsz
   
  - iotop
  - make
  - openssl-devel
  - rpm-build
  - net-snmp
  - net-snmp-devel
  - net-snmp-utils
  - rsync
  - nfs-utils
  - rpcbind
  - pciutils
  - net-tools
  - ntp
