- name: 配置系统内核
  lineinfile:
   dest: /etc/security/limits.conf
   line: '* soft nofile 65535'
  ignore_errors: Ture
- name: 配置系统内核1
  lineinfile:
   dest: /etc/security/limits.conf
   line: '* hard nofile 65535'
  ignore_errors: Ture
