#- name: Ulimit change
#  shell: ulimit -HSn 65535;ulimit -u 81920

#- name: Change limits.conf nofile
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: '\* - nofile [0-9]+'
    #backrefs: no
#    line: '* - nofile 65535'

#- name: Change limits.conf nproc
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: '\* - nproc [0-9]+'
#    #backrefs: no
#    line: '* - nproc 81920'

#- name: Change limits.conf hard
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: '\* - hard [0-9]+'
    #backrefs: no
#        line: '* - hard 65535'

- name: optimization | sysctl.
#
  blockinfile:

    path: /etc/sysctl.conf

    backup: yes

    create: yes

    marker: "# ansible os-init {mark}"

    block: |

      net.ipv4.ip_forward = 1

      net.ipv4.ip_conntrack_max = 1024000

      net.ipv4.ip_local_port_range = 10240 65535

      net.ipv4.tcp_keepalive_time = 600

      net.ipv4.tcp_keepalive_intvl = 30

      net.ipv4.tcp_keepalive_probes = 10

      net.ipv4.tcp_max_tw_buckets = 20480

      net.ipv4.tcp_max_syn_backlog = 8096

      net.ipv4.tcp_synack_retries = 2

      net.ipv4.tcp_fin_timeout = 30

      net.ipv4.tcp_tw_reuse = 1

      net.ipv4.tcp_syncookies = 1

      net.ipv4.conf.all.rp_filter = 0

      net.ipv4.conf.default.rp_filter = 0

      net.ipv4.conf.default.arp_announce = 2

      net.ipv4.conf.lo.arp_announce = 2

      net.ipv4.conf.all.arp_announce = 2   

      net.ipv4.netfilter.ip_conntrack_max = 1024000

      net.ipv4.neigh.default.gc_stale_time = 120

      net.ipv6.conf.all.disable_ipv6 = 1

      net.ipv6.conf.default.disable_ipv6 = 1

      net.ipv6.conf.lo.disable_ipv6 = 1

      # 要求iptables不对bridge的数据进行处理

      net.bridge.bridge-nf-call-ip6tables = 1

      net.bridge.bridge-nf-call-iptables = 1

      net.bridge.bridge-nf-call-arptables = 1

      net.netfilter.nf_conntrack_max = 2310720

      net.core.somaxconn = 262144

      fs.inotify.max_user_watches=89100

      fs.may_detach_mounts = 1

      fs.file-max = 1024000

      fs.nr_open = 1024000

      vm.swappiness = 0

      vm.overcommit_memory=1

      vm.panic_on_oom=0
