---
# tasks file for nginx_keepalived
- name: install epel-release
  yum: name=epel-release state=latest update_cache=yes

- name: install nginx keepalived
  yum:
   name: ['nginx','keepalived']
   state: latest
   update_cache: yes

- name: 复制nginx 配置文件
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes

- name: 复制keepalived配置文件
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes

- name: 复制检测脚本
  copy: src=check_nginx.sh dest=/etc/keepalived/check_nginx.sh backup=yes mode=0755

- name: just force systemd to reread
  systemd: daemon_reload=yes

- name: start nginx
  systemd: name=nginx enabled=yes state=started

- name: start keepalived
  systemd: name=keepalived enabled=yes state=started
