---
# tasks file for init_system
- name: 免密登录
  authorized_key: 
    user: root
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: change name
  raw: "echo {{ hostname|quote }} >/etc/hostname"
- name:
  shell: hostname {{ hostname|quote }}

- name: download centos7 CentOS-Base.repo
  get_url: url=http://mirrors.aliyun.com/repo/Centos-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo 
  tags:
  - CentOS-Base.repo

- name: download centos7 epel.repo
  get_url: url=http://mirrors.aliyun.com/repo/epel-7.repo dest=/etc/yum.repos.d/epel.repo
  tags:
   - epel.repo

- name: stop iptables
  service: name=firewalld state=stopped enabled=no

- name:  replace selinux
  replace: path=/etc/selinux/config regexp="SELINUX=enforcing" replace="SELINUX=disabled" 

- name : stop selinux
  command: /sbin/setenforce 0
  ignore_errors: True

- name: install package
  yum: 
   name: ['vim','man','gcc','gcc-c++','wget','tree','dos2unix','ipmitool','lrzsz','iotop','make','openssl-devel','rpm-build','net-snmp','net-snmp-devel','net-snmp-utils','rsync','nfs-utils','rpcbind','pciutils','net-tools','ntp','bash-completion'] 
   state: latest 
   update_cache: yes
   ignore_errors: True

- name: 配置系统内核
  lineinfile:
   dest: /etc/security/limits.conf
   line: '* soft nofile 65535'
  ignore_errors: True

- name: 配置系统内核1
  lineinfile:
   dest: /etc/security/limits.conf
   line: '* hard nofile 65535'
  ignore_errors: True

- name: optimization | sysctl.
  blockinfile:

    path: /etc/sysctl.conf

    backup: yes

    create: yes

    marker: "# ansible os-init {mark}"

    block: |
     net.ipv6.conf.all.disable_ipv6 = 1
     net.ipv4.tcp_max_syn_backlog = 65536
     net.core.netdev_max_backlog =  32768
     net.core.somaxconn = 32768
     net.ipv4.tcp_timestamps = 0
     net.ipv4.tcp_synack_retries = 2
     net.ipv4.tcp_syn_retries = 2
     net.ipv4.tcp_fin_timeout = 30
     net.ipv4.tcp_syncookies = 1
     #net.nf_conntrack_max = 655360
     #net.netfilter.nf_conntrack_tcp_timeout_established = 1200
     net.ipv4.tcp_tw_recycle = 0
     net.ipv4.tcp_tw_reuse = 1
     net.ipv4.tcp_orphan_retries = 1
     net.ipv4.tcp_max_orphans = 8192
     net.ipv4.ip_local_port_range = 1024 65535
     fs.file-max = 1048576
     net.ipv4.tcp_max_tw_buckets = 6000
- name: 修改时区
  file: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime state=link

- name: sync date
  shell: /usr/sbin/ntpdate  cn.pool.ntp.org

- name: cron date
  cron: minute=0 hour=0 day=* month=* weekday=* name="cron date" backup=yes job='/usr/sbin/ntpdate  cn.pool.ntp.org'

- name: create Directory
  file: path=/data/ state=directory

- name: 修改sshd端口
  lineinfile: path=/etc/ssh/sshd_config regexp="^#Port" line="Port {{SSHD_port}}"

- name: restart sshd
  systemd: name=sshd state=restarted

- name: reboot system
  shell: "sleep 15;reboot"
  async: 10
  poll: 0
  ignore_errors: yes
  tags:
    - reboot
