---
# handlers file for zabbix-proxy

- name: init zabbix db
  mysql_db:
   name: "{{Zabbix_DBname}}"
   login_host: "{{DBHost}}"
   login_user: "{{DBUser}}"
   login_password: "{{DBPassword}}"
   state: import
   target: /usr/share/doc/zabbix-proxy-mysql-{{Zabbix_proxy_version}}/schema.sql.gz

- name: restart zabbix proxy
  systemd: name=zabbix-proxy state=restarted
